INSERT INTO kamaliki_ms_store.author (fullname) VALUES
('J.K. Rowling'),
('George R.R. Martin'),
('Stephen King'),
('Agatha Christie'),
('Isaac Asimov'),
('J.R.R. Tolkien'),
('Ernest Hemingway'),
('Jane Austen'),
('Mark Twain'),
('Leo Tolstoy'),
('Fyodor Dostoevsky'),
('Arthur Conan Doyle'),
('Haruki Murakami'),
('Gabriel García Márquez'),
('Charles Dickens'),
('Franz Kafka'),
('Victor Hugo'),
('Ray Bradbury'),
('Neil Gaiman'),
('Dan Brown');
